## Classification

In [1]:
#import  requried packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/home/sakshi/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [2]:
import warnings
warnings.filterwarnings(action="ignore")

In [3]:
df=pd.read_csv("hearing_test.csv")
df.head()

    age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

# EDA

In [4]:
df.describe()

               age  physical_score  test_result
count  5000.000000     5000.000000  5000.000000
mean     51.609000       32.760260     0.600000
std      11.287001        8.169802     0.489947
min      18.000000       -0.000000     0.000000
25%      43.000000       26.700000     0.000000
50%      51.000000       35.300000     1.000000
75%      60.000000       38.900000     1.000000
max      90.000000       50.000000     1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   float64
 1   physical_score  5000 non-null   float64
 2   test_result     5000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 117.3 KB

In [6]:
df.corr()

                     age  physical_score  test_result
age             1.000000       -0.782146    -0.683171
physical_score -0.782146        1.000000     0.792716
test_result    -0.683171        0.792716     1.000000

In [7]:
# creat x
x=df.drop(['test_result'],axis=1)

# create y
y=df['test_result']

# spilt the data

In [8]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=123456)

In [9]:
x_train

       age  physical_score
448   38.0            43.0
75    82.0            19.4
1774  41.0            42.3
1725  58.0            24.2
1889  45.0            36.0
...    ...             ...
2799  60.0            21.2
171   44.0            28.3
3640  46.0            40.0
3121  47.0            38.1
4594  50.0            33.6

[4000 rows x 2 columns]

# Train the model

In [10]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=5)

model_knn.fit(x_train,y_train)

KNeighborsClassifier()

# fine tunning the hyper parameters

In [11]:
from sklearn.model_selection import GridSearchCV,KFold
from sklearn.neighbors import KNeighborsClassifier

knn= KNeighborsClassifier()

param_grid={
    'n_neighbors' :[3,5,7,9]
}

knn_cv= GridSearchCV(knn,param_grid,cv=5)

knn_cv.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9]})

In [12]:
knn_cv.best_params_

{'n_neighbors': 9}

In [13]:
knn_cv.best_estimator_

KNeighborsClassifier(n_neighbors=9)

In [14]:
knn_cv.best_score_

np.float64(0.9259999999999999)

In [15]:
y_pred =model_knn.predict(x_test)

## evaluation metrics

In [16]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

accuracy= accuracy_score(y_test,y_pred)
precision= precision_score(y_test,y_pred)
recall= recall_score(y_test,y_pred)
f1= f1_score(y_test,y_pred)
roc_auc_score = roc_auc_score(y_test, y_pred)

print(f"Accuracy ={accuracy}")
print(f"Precision ={precision}")
print(f"Recall ={recall}")
print(f"F1 Score ={f1}")
print(f"roc_auc_score = {roc_auc_score}")

Accuracy =0.92
Precision =0.9175911251980983
Recall =0.9538714991762768
F1 Score =0.9353796445880452
roc_auc_score = 0.910777988773889

In [ ]:
## visualize the data