## Read the csv file and add a column

In [1]:
# import the required packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/home/sakshi/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [2]:
df=pd.read_csv("Salary_Data.csv")
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

## EDA

In [3]:
#display first 5 record of dataset
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [5]:
#display last 5 record of dataset
df.tail()

    YearsExperience  Salary
28             10.3  122391
29             10.5  121872
30             11.0  140000
31             12.0  155000
32             13.0  156000

In [6]:
#know the statistical information about  the dataset
df.describe()

       YearsExperience         Salary
count        33.000000      33.000000
mean          5.921212   82760.303030
std           3.342413   34014.620992
min           1.100000   37731.000000
25%           3.200000   56957.000000
50%           5.100000   67938.000000
75%           8.700000  109431.000000
max          13.000000  156000.000000

In [7]:
# basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  33 non-null     float64
 1   Salary           33 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 656.0 bytes

In [8]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [9]:
# to check if there is NaN value or missing value in the dataset
df.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

## add a column

In [10]:
# performing some intermediate operation in data frame(Pre-processing)
# add one more feature / column / variable called as 'Bonus' in the data frame

# add a new column with constant value
df['dummy'] = 100

# add a column named bonus
df['Bonus'] = df['Salary'] + (df['Salary']*0.10)

#add a column named total_salary
df['Total'] = df['Salary'] + df['Bonus']

df.head()

   YearsExperience  Salary  dummy    Bonus    Total
0              1.1   39343    100  43277.3  82620.3
1              1.3   46205    100  50825.5  97030.5
2              1.5   37731    100  41504.1  79235.1
3              2.0   43525    100  47877.5  91402.5
4              2.2   39891    100  43880.1  83771.1